static:
  # Specify the base path to serve your static files from
  publish: ./build

  # Redirect all routes to index.html
  redirects:
    - source: '/*'
      destination: '/index.html'
      status: 200