@startuml 123
class Person{
    name
    email
    phoneNumber
}

class Student{
    student_id
    clubs
    rsvps
}

class FacultyAdministrator{
    admin
    application
}

class Club{
    name
    description
    admins
    memberships
    events
    fundingApplications
}

class Venue{
    name
    location
    capacity
}

class Event{
    title
    description
    date
    time
    venue
    cost
    club
    rsvps
}

class FundingApplication{
    description
    amount
    status
    club
    event
    date
    reviewer
}

class Rsvp{
    student
    event
    state
}

class ticket{
    student
    rsvp
    state
}
Person <|-- Student
Person <|-- FacultyAdministrator
Student "1..*" -- "0..*" Club : belong >
FundingApplication "0..*"--"1" FacultyAdministrator: approval >
Club "1" -- "0..*" Event : hold >
Event  -- "1" Venue : locate >
Student "1" -- "0..*" Rsvp : responded >
Event "1" -- "0..*" Rsvp : contain >
Club "1"--"0..*" FundingApplication : submit >
FundingApplication  -- "0..*" Event : spend on >
Rsvp "1"--"1..3" ticket : contain >
Student "1" -- "0..*" ticket: hold >
@enduml